// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyndicationFeed.Models.Storage.EF;

namespace SyndicationFeed.Server.Migrations
{
    [DbContext(typeof(FeedsContext))]
    [Migration("20190405135250_DeclaredStringPropertiesAsRequiredAndRenamedTable")]
    partial class DeclaredStringPropertiesAsRequiredAndRenamedTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SyndicationFeed.Models.CollectionWithFeeds", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("SyndicationFeed.Models.FeedWithDownloadTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CollectionWithFeedsId");

                    b.Property<string>("SourceAddressString")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CollectionWithFeedsId");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("SyndicationFeed.Models.FeedWithDownloadTime", b =>
                {
                    b.HasOne("SyndicationFeed.Models.CollectionWithFeeds")
                        .WithMany("Feeds")
                        .HasForeignKey("CollectionWithFeedsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
